//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvcControllerModelViewForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
