//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvcControllerModelViewForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Log
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name are required.")]
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        [Range(1, 5, ErrorMessage = "Priority should be between 1 and 5.")]
        public Nullable<int> Priority { get; set; }
    }
}
