//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvcControllerModelViewForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectClient
    {
        public int ProjectClientId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Project Project { get; set; }
    }
}
